name: Lint and upload

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-templates:
    uses: ./.github/workflows/lint-template.yml
  upload-template:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
    needs: [lint-templates]
    uses: ./.github/workflows/upload-template.yml
    with:
      tag: latest
    secrets: inherit
