name: Upload Templates to S3

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Upload template
        run: aws s3 cp template.yml s3://imgproxy-cf/sam/${{ inputs.tag }}/template.yml
